# Generated by Django 4.1.7 on 2023-03-03 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_category_slug_alter_advertisement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
