# Generated by Django 4.1.7 on 2023-03-05 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(8)]),
        ),
    ]
