# Generated by Django 4.1.7 on 2023-03-05 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
